<!DOCTYPE html>
<html>
<head>
    <title>Tap to Earn Game</title>
    <style>
        body {
            text-align: center;
            font-family: Arial, sans-serif;
            background-color: #000000;
            color: white;
            margin: 0;
            padding: 0;
            overflow-x: hidden;
        }
        h1 {
            margin-top: 20px;
            font-size: 2em;
        }
        #tappingIcon {
            width: 150px;
            height: 150px;
            background: linear-gradient(135deg, #ffcc33, #ff9900);
            margin: 50px auto;
            border-radius: 50%;
            line-height: 150px;
            font-size: 24px;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            box-shadow: 0 0 20px #ff9900;
            animation: glow 1s infinite alternate;
        }
        @keyframes glow {
            0% { box-shadow: 0 0 10px #ff9900; }
            100% { box-shadow: 0 0 20px #ff6600; }
        }
        .button {
            margin: 10px;
            padding: 10px 20px;
            font-size: 18px;
            cursor: pointer;
            background: linear-gradient(135deg, #33ccff, #3399ff);
            color: white;
            border: none;
            border-radius: 5px;
            display: inline-block;
            box-shadow: 0 0 10px #3399ff;
            animation: buttonGlow 1s infinite alternate;
        }
        @keyframes buttonGlow {
            0% { box-shadow: 0 0 5px #3399ff; }
            100% { box-shadow: 0 0 15px #3366ff; }
        }
        .buttons {
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
        }
        .sub-buttons {
            margin: 20px 0;
        }
        .sub-button {
            display: block;
            margin: 10px auto;
            padding: 10px;
            background: linear-gradient(135deg, #ffcc33, #ff9900);
            color: black;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            width: 80%;
            box-shadow: 0 0 10px #ff9900;
            animation: buttonGlow 1s infinite alternate;
        }
        #tagline {
            font-size: 1.2em;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <h1>Tap to Earn Game</h1>
    <div id="tappingIcon">Earn</div>
    <p id="score">Score: 0</p>
    <div class="buttons">
        <button class="button" onclick="openReferral()">Referral</button>
        <button class="button" onclick="openBoost()">Boost</button>
        <button class="button" onclick="openAds()">Watch Ads</button>
    </div>
    <p id="tagline">Tap to Earn Big!</p>

    <audio id="tapSound" src="https://www.soundjay.com/button/sounds/button-16.mp3"></audio>

    <script>
        let score = 0;
        const tappingIcon = document.getElementById('tappingIcon');
        const scoreDisplay = document.getElementById('score');
        const tapSound = document.getElementById('tapSound');

        tappingIcon.addEventListener('click', () => {
            score += 1;
            scoreDisplay.textContent = `Score: ${score}`;
            tapSound.play();
        });

        function openReferral() {
            clearSubButtons();
            const subButtons = document.createElement('div');
            subButtons.className = 'sub-buttons';
            subButtons.innerHTML = `
                <button class="sub-button">5 refers = 10000 coins</button>
                <button class="sub-button">10 refers = 25000 coins</button>
                <button class="sub-button">20 refers = 1 Million coins</button>
            `;
            document.body.appendChild(subButtons);
        }

        function openBoost() {
            clearSubButtons();
            const subButtons = document.createElement('div');
            subButtons.className = 'sub-buttons';
            subButtons.innerHTML = `
                <button class="sub-button" onclick="window.open('https://www.x.com/duglucoin')">Follow on X</button>
                <button class="sub-button" onclick="window.open('https://www.t.me/duglucoin')">Join Duglu Community Channel</button>
                <button class="sub-button" onclick="window.open('https://www.youtube.com/duglucoin')">Subscribe to YouTube Channel</button>
            `;
            document.body.appendChild(subButtons);
        }

        function openAds() {
            clearSubButtons();
            const subButtons = document.createElement('div');
            subButtons.className = 'sub-buttons';
            subButtons.innerHTML = `
                <button class="sub-button" onclick="showAd()">Watch Ad 1</button>
                <button class="sub-button" onclick="showAd()">Watch Ad 2</button>
                <button class="sub-button" onclick="showAd()">Watch Ad 3</button>
                <button class="sub-button" onclick="showAd()">Watch Ad 4</button>
                <button class="sub-button" onclick="showAd()">Watch Ad 5</button>
            `;
            document.body.appendChild(subButtons);
        }

        function clearSubButtons() {
            const existingSubButtons = document.querySelector('.sub-buttons');
            if (existingSubButtons) {
                existingSubButtons.remove();
            }
        }

        function showAd() {
            alert('Showing Ad... (Placeholder for real ad integration)');
            // Increment score or boost tapping power as needed
        }
    </script>
</body>
</html>
